export const SET_ORDERS_MODEL = 'orders/SET_ORDERS_MODEL'
export const RECEIVE_ORDERS_DATA = 'orders/RECEIVE_ORDERS_DATA'
export const SET_PROPOSAL_LIST_MODEL= 'orders/SET_PROPOSAL_LIST_MODEL'
export const RECEIVE_PROPOSAL_LIST_DATA='orders/PROPOSAL_LIST_DATA'
