export const SET_USERPROFILE_MODEL = 'userProfile/SET_USERPROFILE_MODEL'
export const RECEIVE_USERPROFILE_DATA = 'userProfile/RECEIVE_USERPROFILE_DATA'
export const SET_HANDLE_SAVE_MODEL = 'userProfile/SET_HANDLE_SAVE_MODEL'
export const RECEIVE_HANDLE_SAVE_DATA = 'userProfile/RECEIVE_HANDLE_SAVE_DATA'
