export const SET_POLICIES_MODEL = 'policies/SET_POLICIES_MODEL'
export const RECEIVE_POLICIES_DATA = 'policies/RECEIVE_POLICIES_DATA'
export const SET_POLICY_LIST_MODEL= 'orders/SET_POLICY_LIST_MODEL'
export const RECEIVE_POLICY_LIST_DATA='orders/POLICY_LIST_DATA'