export const SET_QUOTATIONS_MODEL = 'quotations/SET_QUOTATIONS_MODEL'
export const RECEIVE_QUOTATIONS_DATA = 'quotations/RECEIVE_QUOTATIONS_DATA'
export const SET_QUOTATION_LIST_MODEL= 'orders/SET_QUOTATION_LIST_MODEL'
export const RECEIVE_QUOTATION_LIST_DATA='orders/QUOTATION_LIST_DATA'