export const illusType = {
  1: 'Sum Assured',
  2: 'Accumulated Premium',
  3: 'Annual Basic Premium',
  4: 'Regular Topup Premium',
  5: 'Annual Investment Premium',
  6: 'Annual Invest Top-up',
  7: 'COI',
  8: 'Annual Admin Cost',
  9: 'Total Charges Deducted',
  10: 'Fund Net Value',
  11: 'Basic Yearly Return',
  12: 'Basic Investment Fee',
  13: 'Total Investment Value',
  14: 'Net Premium',
  15: 'Regular Investment Premium',
  16: 'Total Investment Premium',
  17: 'Cash Value',
  18: 'Paidup Value',
  19: 'Cash Bonus',
  20: 'Survival Benefit',
  21: 'Surrender Value',
  22: 'Death Benefit',
  23: 'Maturity Amount',
  24: 'RB Surrender Value',
  25: 'Annuity Payment',
  26: 'GMDB Amount',
  27: 'GMAB Amount',
  28: 'GMWB Amount',
  29: 'GMIB Amount',
  30: 'Annual Withdraw Amount',
  31: 'Annual Recurring Top-up',
  32: 'Adhoc Topup',
  33: 'Adhoc Topup Investment Part',
  34: 'Fund Management Fee',
  35: 'Total Fund Value',
  36: 'Accumulated Topup',
  37: 'Accumulated Cash Bonus',
  38: 'Accumulated Reversionary Bonus',
  39: 'Accumulated Survival Benefit',
  40: 'Accumulated Survival Benefit',
  41: 'Policyholder Waiver Benefit',
  42: 'Insured Waiver Benefit',
  43: 'Total and Permanent Disability Benefit',
  44: 'Disability Benefit',
  45: 'Light Disease Benefit',
  46: 'Heavy Disease Benefit',
  47: 'Disease End Stage Benefit',
  48: 'Specific Disease Benefit',
  49: 'Medical Insurance Benefit',
  50: 'Universal Account',
  51: 'Disease Death Benefit',
  52: 'Nursing Benefit',
  53: 'Specific Heavy Disease Benefit',
  54: 'Death Benefit MAX',
  55: 'Light Disease Benefit MAX',
  56: 'Specific Disease Benefit MAX',
  57: 'Heavy Disease Benefit MAX',
  58: 'Disability Benefit MAX',
  59: 'Disease End Stage Benefit MAX',
  60: 'Accidental Disability Benefit MAX',
  61: 'Medical Insurance Benefit MAX',
  62: 'Death Benefit (L)',
  63: 'Death Benefit (M)',
  64: 'Death Benefit (H)',
  65: 'Additional Death/Disease Benefit',
  66: 'Accidental Death Benefit MAX',
  67: 'Projection of Value (L)',
  68: 'Projection of Value (M)',
  69: 'Projection of Value (H)',
  70: 'Accidental Disability Benefit',
  71: 'Total and Permanent Disability Benefit MAX',
  72: 'Moderate Disease Benefit',
  73: 'Moderate Disease Benefit MAX',
  163: 'Guranteed Benefit',
  170: 'Total and Permanent Disability Benefit',
  175: 'TCV',
  177: 'SA after CV withdraw',
  179: 'TCA',
  183: 'GCV',
  184: 'NGCV',
  185: 'GCA',
  186: 'NGCA',
  187: 'Premium Total',
  188: 'Allocated Premium',
  189: 'Monthly Cost of Cover',
  190: 'Monthly Interest',
  191: 'Month End Fund Value',
  192: 'Monthly Sum at Risk',
  193: 'Allocated premium (Equity)',
  194: 'Allocated premium (Managed)',
  195: 'Allocated premium (Fixed)',
  196: 'Start Fund (Equity)',
  197: 'Start Fund (Managed)',
  198: 'Start Fund (Fixed)',
  199: 'Charge for Cost of Cover (Equity)',
  200: 'Charge for Cost of Cover (Managed)',
  201: 'Charge for Cost of Cover (Fixed)',
  202: 'Switching charge (Equity)',
  203: 'Switching charge (Managed)',
  204: 'Switching charge (Fixed)',
  205: 'Administration charge (Equity)',
  206: 'Administration charge (Managed)',
  207: 'Administration charge (Fixed)',
  208: 'Investment income (Equity)',
  209: 'Investment income (Managed)',
  210: 'Investment income (Fixed)',
  211: 'Fund before mgt charge (Equity)',
  212: 'Fund before mgt charge (Managed)',
  213: 'Fund before mgt charge (Fixed)',
  214: 'Fund mgt charge (Equity)',
  215: 'Fund mgt charge (Managed)',
  216: 'Fund mgt charge (Fixed)',
  217: 'Fund at month end (Equity)',
  218: 'Fund at month end (Managed)',
  219: 'Fund at month end (Fixed)',
  220: 'Sum at Risk (Equity)',
  221: 'Sum at Risk (Managed)',
  222: 'Sum at Risk (Fixed)',
  223: 'Total End Fund',
  224: 'Cashflow of PH',
  225: 'Total Sum at Risk',
  226: 'Waiver Premium',
  227: 'Loyalty Bonus',
  228: 'Last Month End Basic Prem TIV(RB1)',
  229: 'Last Month End Basic Prem TIV(RE1)',
  230: 'Last Month End Basic Prem TIV(RF1)',
  231: 'Last Month End Basic Prem TIV(RJ1)',
  232: 'Last Month End Top Up TIV(RB1)',
  233: 'Last Month End Top Up TIV(RE1)',
  234: 'Last Month End Top Up TIV(RF1)',
  235: 'Last Month End Top Up TIV(RJ1)',
  236: 'Original Death Benefit',
  237: 'Additional Death Benefit',
  990: 'Admin Charge',
  991: 'COI Charge',
  992: 'Supply Charge',
  993: 'Adhoc Topup Charge',
  994: 'Adhoc Policy Fee',
  995: 'Recurring Topup Charge',
  996: 'Unapplied Premium',
}
