/**
 * Created by haydn.chen on 4/8/2018.
 */
export const jobCate = {
  "1": "Accountant",
  "2": "Actor",
  "3": "Actress",
  "4": "Actuary",
  "5": "Adjuster",
  "6": "Administrator",
  "7": "Advertising Agent",
  "8": "Advertising Manager",
  "9": "Advisor",
  "10": "Advocate",
  "11": "Aerial erector",
  "12": "Aerobics teacher",
  "14": "Agent (entertainment)",
  "16": "Property agent",
  "17": "Agriculture worker",
  "18": "Air conditioning installer",
  "19": "Air steward",
  "20": "Air stewardess",
  "21": "Air traffic controller",
  "22": "Aircraft designer",
  "23": "Aircraft engineer",
  "24": "Aircraft mechanic",
  "25": "Aircraft technician",
  "26": "Ambassador",
  "27": "Analyst",
  "28": "Anaesthetist",
  "29": "Animal trainer",
  "30": "Architect",
  "33": "Armed forces",
  "34": "Army officer",
  "35": "Artist (freelance)",
  "36": "Artist (salaried)",
  "37": "Aircraft assembler",
  "38": "Electrical goods assembler",
  "39": "Auctioneer",
  "40": "Auditor",
  "41": "Author",
  "42": "Baby sitter",
  "43": "Baker",
  "44": "Banker",
  "45": "Bank teller",
  "46": "Barber",
  "47": "Barrister",
  "48": "Bartender",
  "49": "Beautician",
  "50": "Blacksmith",
  "51": "Blaster",
  "52": "Bleach worker",
  "53": "Boat builder",
  "54": "Boatman",
  "55": "Boatswain",
  "56": "Bodyguard",
  "57": "Boiler worker",
  "58": "Bomb disposal officer",
  "60": "Bouncer",
  "61": "Brewer",
  "62": "Bricklayer",
  "63": "Broker",
  "64": "Butcher",
  "65": "Buyer",
  "66": "Cabinet maker",
  "67": "Cable installer (television)",
  "68": "Calligrapher",
  "69": "Cane worker",
  "70": "Canvasser",
  "71": "Car salesman",
  "72": "Caretaker",
  "73": "Carpark worker",
  "74": "Carpenter",
  "75": "Cashier",
  "76": "Caterer",
  "77": "Ceiling fitter",
  "78": "Cement worker",
  "79": "Ceramics worker",
  "81": "Chancellor",
  "82": "Chauffeur",
  "83": "Chef",
  "84": "Chemical worker",
  "85": "Chemist",
  "86": "CEO",
  "87": "Child",
  "88": "Chinese physician (sinseh)",
  "89": "Chiropractor",
  "90": "Cinema projectionist",
  "92": "Civil servant",
  "93": "Cleaner (with height involvement)",
  "94": "Cleaner (with no height involvement)",
  "95": "Clerical worker",
  "96": "Clerk (handling goods)",
  "97": "Cobbler",
  "98": "Coffee shop helper",
  "99": "Columnist",
  "100": "Column writer",
  "102": "Computer programmer",
  "103": "Computer software engineer",
  "104": "Computer technician",
  "105": "Composer",
  "106": "Concrete erector",
  "107": "Concrete mixer driver",
  "108": "Construction foreman",
  "109": "Construction worker (with height involvement)",
  "110": "Construction worker (with no height involvement)",
  "111": "Cook",
  "112": "Coroner",
  "113": "Court assistant",
  "114": "Crane operator",
  "115": "Croupier",
  "116": "Curtain fitter",
  "117": "Customer service worker",
  "118": "Customs officer",
  "119": "Cutter",
  "120": "Dairy worker",
  "121": "Dancer (freelance)",
  "122": "Dancer (salaried)",
  "123": "Dancing instructor",
  "124": "Data processing clerk",
  "125": "Dealer",
  "126": "Debt collector",
  "127": "Decorator",
  "128": "Delivery worker",
  "129": "Demolition worker",
  "130": "Dental therapist",
  "131": "Dentist",
  "132": "Designer",
  "133": "Despatch worker",
  "134": "Diamond cutter",
  "135": "Dietician",
  "136": "Director",
  "137": "Disc jockey",
  "138": "Dispenser",
  "139": "Diver",
  "141": "Doctor (except those in mental hospital)",
  "142": "Doctor (mental hospital)",
  "143": "Domestic servant",
  "144": "Draughtsman",
  "145": "Dressmaker",
  "148": "Driver (bus)",
  "149": "Excavator driver",
  "152": "Driver (train)",
  "155": "Delivery driver",
  "156": "Driving examiner",
  "157": "Driving instructor",
  "158": "Dry cleaner",
  "159": "Dye worker",
  "160": "Film editor",
  "161": "Newspaper editor",
  "162": "Electrician",
  "163": "Engineer officer",
  "165": "Engraver",
  "166": "Entertainer",
  "167": "Escort",
  "168": "Executive",
  "169": "Executive director",
  "170": "Exhibition coordinator",
  "171": "Factory machinist",
  "172": "Farmer",
  "173": "Film director",
  "174": "Film producer",
  "175": "Film critic",
  "176": "Film developer",
  "177": "Finance administrator",
  "178": "Fireman",
  "179": "Fisherman",
  "181": "Fishmonger",
  "182": "Fitness Centre instructor",
  "183": "Fitter",
  "184": "Floor layer",
  "185": "Florist",
  "186": "Foreman",
  "187": "Fortune teller",
  "188": "Freezer worker",
  "189": "Fruit seller",
  "190": "Gardener",
  "191": "Geologist",
  "193": "Glass worker",
  "194": "Goldsmith",
  "195": "Golf caddie",
  "196": "Greengrocer",
  "197": "Gynaecologist",
  "198": "Hairdresser",
  "199": "Hawker",
  "200": "Hoist operator",
  "201": "Hotel manager",
  "202": "Housekeeper",
  "203": "Housemaid",
  "204": "Housewife",
  "205": "Immigration officer",
  "206": "Incinerator plant operator",
  "207": "Information system personnel",
  "208": "Transport inspector",
  "209": "Interior decorator",
  "210": "Interpreter (no overseas/ dangerous assignment)",
  "211": "Interpreter (overseas/ dangerous assignment)",
  "212": "Janitor",
  "213": "Jockey",
  "214": "Journalist (no overseas/dangerous assignment)",
  "215": "Journalist (overseas/dangerous assignment)",
  "216": "Judge",
  "217": "Kindergarten teacher",
  "218": "Laboratory assistant",
  "219": "Laundryman",
  "220": "Lawyer",
  "221": "Lecturer",
  "222": "Legal personnel",
  "223": "Librarian",
  "224": "Life guard",
  "225": "Lithographer",
  "226": "Locksmith",
  "227": "Lorry attendant",
  "228": "Lumberjack",
  "229": "Machine fitter",
  "230": "Machine operator",
  "231": "Machinist",
  "232": "Magician",
  "233": "Magistrate",
  "234": "Makeup artist",
  "235": "Management consultant",
  "236": "Management personnel",
  "237": "Management trainee",
  "238": "Manager",
  "248": "Marine engineer",
  "253": "Marine personnel (oil carrying vessel)",
  "255": "Marine pilot",
  "259": "Market research interviewer",
  "260": "Martial arts instructor",
  "261": "Masseur",
  "262": "Masseuse",
  "263": "Mechanic",
  "264": "Medical consultant",
  "265": "Medium",
  "266": "Messenger",
  "267": "Metal polisher",
  "268": "Metal worker",
  "273": "Pilot helicopter (armed forces)",
  "276": "Model",
  "277": "Modelling agency manager",
  "278": "Money changer",
  "279": "Monk",
  "280": "Mortuary worker",
  "281": "Motor technician",
  "282": "Moulder",
  "283": "Mountaineer",
  "284": "Museum worker",
  "285": "Music teacher (Others)",
  "286": "Music teacher (school)",
  "287": "Musician",
  "288": "Musical instrument tuner",
  "289": "National service man",
  "290": "News photographer (travel)",
  "291": "News photographer (without travel)",
  "292": "Newsvendor",
  "293": "Night club manager",
  "294": "Night watchman",
  "295": "Nun",
  "296": "Nurse",
  "297": "Obstetrician",
  "298": "Odd-job worker",
  "299": "Office messenger",
  "300": "Oil rig consultant",
  "301": "Oil rig engineer",
  "302": "Oil rig salesperson",
  "303": "Oil rig worker",
  "304": "Optician",
  "305": "Packer",
  "306": "Painter",
  "307": "Panel beater",
  "308": "Paper maker",
  "309": "Parachutist",
  "310": "Park keeper",
  "311": "Pattern maker",
  "312": "Personal assistant",
  "313": "Personal trainer",
  "314": "Personnel officer",
  "315": "Pest control worker",
  "316": "Pet breeder",
  "317": "Pharmacist",
  "318": "Photographer",
  "319": "Physician",
  "320": "Physiotherapist",
  "321": "Piano teacher",
  "322": "Pilot (armed forces)",
  "323": "Commercial pilot",
  "325": "Pipe fitter",
  "326": "Planning officer",
  "327": "Plasterer",
  "328": "Plumber",
  "329": "Policeman",
  "330": "Politician",
  "332": "Postman",
  "333": "Poultry farm worker",
  "334": "Power station worker",
  "335": "Priest",
  "336": "Principal",
  "337": "Prison warden",
  "338": "Private detective",
  "339": "Probation officer",
  "340": "Production operator",
  "341": "Production worker",
  "342": "Professor",
  "343": "Prop man",
  "344": "Psychiatrist",
  "345": "Public relations officer",
  "346": "Publisher",
  "347": "Purchaser",
  "348": "Quality control officer",
  "350": "Quarry worker",
  "351": "Racehorse trainer",
  "352": "Radiographer",
  "353": "Rag bone dealer",
  "354": "Railway worker",
  "355": "Ranger",
  "356": "Receptionist",
  "357": "Referee",
  "358": "Refuse collector",
  "359": "Registrar",
  "360": "Remisier",
  "361": "Researcher",
  "362": "Reservoir worker",
  "363": "Retired",
  "365": "Road safety officer",
  "366": "Road sweeper",
  "367": "Roofer",
  "368": "Rugby player",
  "369": "Sales assistant",
  "370": "Sales consultant",
  "371": "Sales executive",
  "372": "Sales manager",
  "373": "Sales representative",
  "374": "Sand blaster",
  "375": "Saw miller",
  "376": "Scaffolder",
  "377": "Scientific officer",
  "378": "Scientist",
  "379": "Secretary",
  "380": "Security guard",
  "381": "Self-employed",
  "382": "Sewage worker",
  "383": "Shipping officer",
  "384": "Shipyard worker",
  "385": "Shoe repairer",
  "386": "Shop assistant",
  "387": "Shop keeper",
  "388": "Shop manager",
  "389": "Signalman",
  "390": "Signwriter",
  "391": "Slaughterer",
  "392": "Social worker",
  "393": "Sole proprietor",
  "394": "Solicitor",
  "395": "Sports coach",
  "396": "Sportsman (professional)",
  "397": "Spray painter",
  "398": "Station master",
  "399": "Steel worker",
  "400": "Steel erector",
  "401": "Stenographer",
  "403": "Stockbroker",
  "404": "Stock taker",
  "405": "Stone restorer",
  "406": "Store keeper",
  "407": "Storeman",
  "408": "Student",
  "409": "Stuntman",
  "410": "Sub-editor",
  "411": "Supervisor",
  "412": "Supplier",
  "413": "Surveyor",
  "414": "Sweeper",
  "415": "Swimming instructor",
  "416": "Swimming pool attendant",
  "417": "Systems engineer",
  "418": "Tailor",
  "419": "Tar worker",
  "420": "Tattooist",
  "421": "Taxation personnel",
  "422": "Teacher (education)",
  "423": "Teacher (others)",
  "425": "Fuel technician (oil/gas rigs)",
  "427": "Telephone operator",
  "428": "Television presenter",
  "429": "Textile worker",
  "430": "Toolmaker",
  "431": "Tour manager",
  "432": "Tourist guide",
  "433": "Tower crane driver",
  "434": "Traffic warden",
  "435": "Train crew",
  "436": "Train driver",
  "437": "Travel agent",
  "438": "Tutor",
  "439": "Typist",
  "440": "Tyre worker",
  "441": "Undertaker",
  "442": "Unemployed",
  "443": "Upholsterer",
  "444": "Usher",
  "445": "Valuer",
  "446": "Veterinarian",
  "447": "Veterinary assistant",
  "450": "Waiter",
  "451": "Waitress",
  "452": "Wall paper hanger",
  "453": "Warehouse worker",
  "454": "Washer",
  "455": "Washroom worker",
  "456": "Water treatment plant worker",
  "457": "Weaver",
  "458": "Welder",
  "459": "Wholesaler",
  "460": "Wood carver",
  "461": "Zoo keeper",
  "462": "Zoologist",
}

export const bankName = {
  "UNITTEST": "Unit Test Bank"
}

export const paymentFreq = {
  "1": 'Yearly',
  "2": 'Half-Yearly',
  "3": 'Quarterly',
  "4": 'Monthly',
  "5": 'Single Premium',
  "0": 'NA',
  "8": 'Daily',
}

export const chargePeriod = {
  "0": 'NA',
  "1": 'Single Premium',
  "2": '{0} Years',
  "3": 'To Age {0}',
  "4": 'Whole Life',
}

export const coveragePeriod = {
  "0": 'NA',
  "1": 'Whole Life',
  "2": '{0} Years',
  "3": 'To Age {0}',
  "4": '{0} Months',
  "5": '{0} Days',
}

export const payPeriod = {
  "0": 'NA',
  "1": 'Immediate',
  "2": 'Start from Age {0}',
  "3": 'After {0} Years',
  "4": 'Age of Birthday',
  "5": 'Start at Anniversary Date',
}

export const proposalStatus = {
  "31": 'Waiting for Underwriting', // generated or none underwriting
  "79": 'Underwriting Pass', // underwriting passed
  "82": 'Underwriting Failed', // underwriting failed, can retry underwriting
  "80": 'Accepted', // accept or waiting for payment
  "87": 'Payment Failed', // payment failed, can retry issue
  "85": 'Issued', // issued
  "88": 'Invalid', // deleted or invalid
  "89": 'Waiting for Payment Result', // waiting for payment response, usually for online payment callback
  "90": 'Payed', // payed but not issued, usually error happens on online payment callback, can retry issue
  "91": 'Issue Failed' // issued failed, can retry issue
}
